import type {
  Facility,
  Medicine,
  Need,
  Production,
  Route,
} from "@/domain/supply-network";

export interface SupplyNetworkSeed {
  facilities: Facility[];
  medicines: Medicine[];
  routes: Route[];
  production: Production[];
  needs: Need[];
}

export const seedData: SupplyNetworkSeed = {
  facilities: [
    {
      id: "medigen-pune",
      name: "Medigen Biologics",
      kind: "manufacturer",
      city: "Pune",
      region: "Maharashtra",
      country: "India",
      capacity: 84_000,
      subtitle: "Sterile injectables plant",
    },
    {
      id: "novabio-hyderabad",
      name: "NovaBio Health",
      kind: "manufacturer",
      city: "Hyderabad",
      region: "Telangana",
      country: "India",
      capacity: 72_000,
      subtitle: "Maternal health medicines",
    },
    {
      id: "vitalis-ahmedabad",
      name: "Vitalis Pharma",
      kind: "supplier",
      city: "Ahmedabad",
      region: "Gujarat",
      country: "India",
      capacity: 96_000,
      subtitle: "Respiratory & rehydration supply",
    },
    {
      id: "coastal-goa",
      name: "Coastal Generics",
      kind: "supplier",
      city: "Panaji",
      region: "Goa",
      country: "India",
      capacity: 52_000,
      subtitle: "Essential generics partner",
    },
    {
      id: "hub-sahyadri",
      name: "Sahyadri Health Hub",
      kind: "hub",
      city: "Pune",
      region: "Maharashtra",
      country: "India",
      capacity: 118_000,
      subtitle: "Western regional distribution",
    },
    {
      id: "hub-konkan",
      name: "Konkan Cold Chain",
      kind: "hub",
      city: "Mumbai",
      region: "Maharashtra",
      country: "India",
      capacity: 104_000,
      subtitle: "Temperature-controlled logistics",
    },
    {
      id: "hub-central",
      name: "Central Care Depot",
      kind: "hub",
      city: "Nagpur",
      region: "Maharashtra",
      country: "India",
      capacity: 92_000,
      subtitle: "Central India distribution",
    },
    {
      id: "hub-deccan",
      name: "Deccan Medical Link",
      kind: "hub",
      city: "Hyderabad",
      region: "Telangana",
      country: "India",
      capacity: 88_000,
      subtitle: "Southern corridor hub",
    },
    {
      id: "clinic-nashik",
      name: "Hope Community Clinic",
      kind: "clinic",
      city: "Nashik",
      region: "Maharashtra",
      country: "India",
      capacity: 1_850,
      subtitle: "Primary & diabetes care",
    },
    {
      id: "clinic-nagpur",
      name: "Sunrise District Hospital",
      kind: "clinic",
      city: "Nagpur",
      region: "Maharashtra",
      country: "India",
      capacity: 3_400,
      subtitle: "District referral hospital",
    },
    {
      id: "clinic-solapur",
      name: "Lotus Care Centre",
      kind: "clinic",
      city: "Solapur",
      region: "Maharashtra",
      country: "India",
      capacity: 2_100,
      subtitle: "Women & children care",
    },
    {
      id: "clinic-kolhapur",
      name: "Riverbend Medical Centre",
      kind: "clinic",
      city: "Kolhapur",
      region: "Maharashtra",
      country: "India",
      capacity: 1_620,
      subtitle: "Rural referral centre",
    },
    {
      id: "clinic-satara",
      name: "Asha Rural Health",
      kind: "clinic",
      city: "Satara",
      region: "Maharashtra",
      country: "India",
      capacity: 1_280,
      subtitle: "Rural primary care network",
    },
    {
      id: "clinic-aurangabad",
      name: "Sanjeevani Hospital",
      kind: "clinic",
      city: "Aurangabad",
      region: "Maharashtra",
      country: "India",
      capacity: 2_760,
      subtitle: "Emergency & maternal care",
    },
  ],
  medicines: [
    { id: "insulin", name: "Human insulin", category: "Diabetes", coldChain: true },
    { id: "adrenaline", name: "Adrenaline", category: "Emergency", coldChain: false },
    { id: "amoxicillin", name: "Amoxicillin", category: "Antibiotic", coldChain: false },
    { id: "oxytocin", name: "Oxytocin", category: "Maternal health", coldChain: true },
    { id: "salbutamol", name: "Salbutamol", category: "Respiratory", coldChain: false },
    { id: "ors", name: "Oral rehydration salts", category: "Essential care", coldChain: false },
  ],
  production: [
    { facilityId: "medigen-pune", medicineId: "insulin", monthlyCapacity: 28_000 },
    { facilityId: "medigen-pune", medicineId: "adrenaline", monthlyCapacity: 42_000 },
    { facilityId: "novabio-hyderabad", medicineId: "amoxicillin", monthlyCapacity: 48_000 },
    { facilityId: "novabio-hyderabad", medicineId: "oxytocin", monthlyCapacity: 24_000 },
    { facilityId: "vitalis-ahmedabad", medicineId: "salbutamol", monthlyCapacity: 52_000 },
    { facilityId: "vitalis-ahmedabad", medicineId: "ors", monthlyCapacity: 64_000 },
    { facilityId: "coastal-goa", medicineId: "amoxicillin", monthlyCapacity: 31_000 },
    { facilityId: "coastal-goa", medicineId: "ors", monthlyCapacity: 38_000 },
    { facilityId: "coastal-goa", medicineId: "insulin", monthlyCapacity: 16_000 },
  ],
  needs: [
    { clinicId: "clinic-nashik", medicineId: "insulin", weeklyUnits: 720, criticality: "essential" },
    { clinicId: "clinic-nashik", medicineId: "salbutamol", weeklyUnits: 460, criticality: "important" },
    { clinicId: "clinic-nashik", medicineId: "ors", weeklyUnits: 620, criticality: "important" },
    { clinicId: "clinic-nagpur", medicineId: "insulin", weeklyUnits: 980, criticality: "essential" },
    { clinicId: "clinic-nagpur", medicineId: "adrenaline", weeklyUnits: 320, criticality: "essential" },
    { clinicId: "clinic-nagpur", medicineId: "amoxicillin", weeklyUnits: 1_240, criticality: "important" },
    { clinicId: "clinic-solapur", medicineId: "oxytocin", weeklyUnits: 540, criticality: "essential" },
    { clinicId: "clinic-solapur", medicineId: "amoxicillin", weeklyUnits: 860, criticality: "important" },
    { clinicId: "clinic-solapur", medicineId: "ors", weeklyUnits: 720, criticality: "important" },
    { clinicId: "clinic-kolhapur", medicineId: "insulin", weeklyUnits: 510, criticality: "essential" },
    { clinicId: "clinic-kolhapur", medicineId: "ors", weeklyUnits: 840, criticality: "important" },
    { clinicId: "clinic-satara", medicineId: "salbutamol", weeklyUnits: 390, criticality: "essential" },
    { clinicId: "clinic-satara", medicineId: "adrenaline", weeklyUnits: 180, criticality: "essential" },
    { clinicId: "clinic-satara", medicineId: "amoxicillin", weeklyUnits: 570, criticality: "important" },
    { clinicId: "clinic-aurangabad", medicineId: "oxytocin", weeklyUnits: 680, criticality: "essential" },
    { clinicId: "clinic-aurangabad", medicineId: "adrenaline", weeklyUnits: 290, criticality: "essential" },
    { clinicId: "clinic-aurangabad", medicineId: "amoxicillin", weeklyUnits: 940, criticality: "important" },
  ],
  routes: [
    { id: "r01", from: "medigen-pune", to: "hub-sahyadri", leadTimeHours: 3, reliability: 0.98, mode: "road" },
    { id: "r02", from: "medigen-pune", to: "hub-konkan", leadTimeHours: 5, reliability: 0.96, mode: "road" },
    { id: "r03", from: "novabio-hyderabad", to: "hub-deccan", leadTimeHours: 2, reliability: 0.99, mode: "road" },
    { id: "r04", from: "novabio-hyderabad", to: "hub-sahyadri", leadTimeHours: 10, reliability: 0.93, mode: "road" },
    { id: "r05", from: "vitalis-ahmedabad", to: "hub-konkan", leadTimeHours: 8, reliability: 0.95, mode: "road" },
    { id: "r06", from: "vitalis-ahmedabad", to: "hub-central", leadTimeHours: 12, reliability: 0.91, mode: "rail" },
    { id: "r07", from: "coastal-goa", to: "hub-konkan", leadTimeHours: 9, reliability: 0.94, mode: "road" },
    { id: "r08", from: "coastal-goa", to: "hub-sahyadri", leadTimeHours: 7, reliability: 0.95, mode: "road" },
    { id: "r09", from: "hub-sahyadri", to: "hub-central", leadTimeHours: 9, reliability: 0.93, mode: "rail" },
    { id: "r10", from: "hub-konkan", to: "clinic-nashik", leadTimeHours: 4, reliability: 0.95, mode: "road" },
    { id: "r11", from: "hub-konkan", to: "clinic-kolhapur", leadTimeHours: 8, reliability: 0.92, mode: "road" },
    { id: "r12", from: "hub-sahyadri", to: "clinic-nashik", leadTimeHours: 5, reliability: 0.97, mode: "road" },
    { id: "r13", from: "hub-sahyadri", to: "clinic-satara", leadTimeHours: 3, reliability: 0.98, mode: "road" },
    { id: "r14", from: "hub-sahyadri", to: "clinic-solapur", leadTimeHours: 5, reliability: 0.96, mode: "road" },
    { id: "r15", from: "hub-deccan", to: "clinic-solapur", leadTimeHours: 6, reliability: 0.94, mode: "road" },
    { id: "r16", from: "hub-deccan", to: "clinic-aurangabad", leadTimeHours: 8, reliability: 0.91, mode: "road" },
    { id: "r17", from: "hub-central", to: "clinic-nagpur", leadTimeHours: 2, reliability: 0.99, mode: "road" },
    { id: "r18", from: "hub-central", to: "clinic-aurangabad", leadTimeHours: 5, reliability: 0.95, mode: "road" },
    { id: "r19", from: "hub-central", to: "clinic-satara", leadTimeHours: 11, reliability: 0.89, mode: "road" },
  ],
};
